export const LIST_INIT = "LIST_INIT";
export const LIST_SUCCESS = "LIST_SUCCESS";
export const LIST_FAILURE = "LIST_FAILURE";
export const LIST_ADD = "LIST_ADD";
export const LIST_ADD_SUCCESS = "LIST_ADD_SUCCESS";
export const LIST_ADD_FAILURE = "LIST_ADD_FAILURE";
export const LIST_REMOVE = "LIST_REMOVE";
export const LIST_REMOVE_SUCCESS = "LIST_REMOVE_SUCCESS";
export const LIST_REMOVE_FAILURE = "LIST_REMOVE_FAILURE";

export const PANTRY_INIT = "PANTRY_INIT";
export const PANTRY_INIT_SUCCESS = "PANTRY_INIT_SUCCESS";
export const PANTRY_INIT_FAILURE = "PANTRY_INITFAILURE";
export const PANTRY_ADD = "PANTRY_ADD";
export const PANTRY_ADD_SUCCESS = "PANTRY_ADD_SUCCESS";
export const PANTRY_ADD_FAILURE = "PANTRY_ADD_FAILURE";

export const RECIPE_FAV = "RECIPE_FAV";
export const RECIPE_FAV_SUCCESS = "RECIPE_FAV_SUCCESS";
export const RECIPE_FAV_FAILURE = "RECIPE_FAV_FAILURE";
export const RECIPE_FAV_ADD = "RECIPE_FAV_ADD";
export const RECIPE_FAV_ADD_SUCCESS = "RECIPE_FAV_ADD_SUCCESS";
export const RECIPE_FAV_ADD_FAILURE = "RECIPE_FAV_ADD_FAILURE";
export const RECIPE_SEARCH_INIT = "RECIPE_SEARCH_INIT";
export const RECIPE_SEARCH_SUCCESS = "RECIPE_SEARCH_SUCCESS";
export const RECIPE_SEARCH_FAILURE = "RECIPE_SEARCH_FAILURE";

export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const USER_ADD_SUCCESS = "USER_ADD_SUCCESS";
