export const LIST_INIT = "LIST_INIT";
export const LIST_SUCCESS = "LIST_SUCCESS";
export const LIST_FAILURE = "LIST_FAILURE";
export const LIST_ADD = "LIST_ADD";
export const LIST_ADD_SUCCESS = "LIST_ADD_SUCCESS";
export const LIST_ADD_FAILURE = "LIST_ADD_FAILURE";
export const LIST_REMOVE = "LIST_REMOVE";
export const LIST_REMOVE_SUCCESS = "LIST_REMOVE_SUCCESS";
export const LIST_REMOVE_FAILURE = "LIST_REMOVE_FAILURE";

export const PANTRY_INIT = "PANTRY_INIT";
export const PANTRY_INIT_SUCCESS = "PANTRY_INIT_SUCCESS";
export const PANTRY_INIT_FAILURE = "PANTRY_INITFAILURE";
export const PANTRY_ADD = "PANTRY_ADD";
export const PANTRY_ADD_SUCCESS = "PANTRY_ADD_SUCCESS";
export const PANTRY_ADD_FAILURE = "PANTRY_ADD_FAILURE";
